module.exports = [
  {
    id: '1',
    numberId: 1018071456,
    name: 'Pedro',
    lastName: 'Goméz',
    email: 'pedro@gmail.com',
    contactNumber: 314685940,
    username: 'luis.parra.1661',
    rol: 'admin',
    deleted: false,
  },
  {
    id: '2',
    numberId: 2021561,
    name: 'Juan',
    lastName: 'Rodriguez',
    email: 'juan@gmail.com',
    contactNumber: 315685940,
    username: 'juanito',
    rol: 'doctor',
    deleted: false,
  },
  {
    id: '3',
    numberId: 6465161,
    name: 'Andres',
    lastName: 'Suarez',
    email: 'andres@gmail.com',
    contactNumber: 316585940,
    username: 'andreses',
    rol: 'bacteriologist',
    deleted: false,
  },
  {
    id: '4',
    numberId: 85461654,
    name: 'Paula',
    lastName: 'Silva',
    email: 'paula@gmail.com',
    contactNumber: 3154549216,
    username: 'paulaaa',
    rol: 'patient',
    deleted: false,
  },
  {
    id: '6',
    numberId: 54651564,
    name: 'Raul',
    lastName: 'Silva',
    email: 'raul@gmail.com',
    contactNumber: 3154549216,
    username: 'raulll',
    rol: 'doctor',
    deleted: false,
  },
  {
    id: 'y_8-e_lXKGTff8MxcTbPb',
    numberId: 1018071561,
    name: 'luis',
    lastName: 'parra',
    email: 'luis@gmail.com',
    contactNumber: '3145888791',
    rol: 'admin',
    deleted: false,
    username: 'luis.parra.1564',
  },
];
